on:
  push:
  pull_request:

name: Test & Build Release
jobs:
  
  Build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - run: bash .cross_compile.sh
      
      - name: Get date
        run: echo "date=$(date +'%m/%d_%Y_%H/%M')" >> $GITHUB_ENV
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          path: dist/
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.REPO_TOKEN }}"
          files: dist/  
          prerelease: false
          automatic_release_tag: ${{ env.date }}
     
